/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * logitry
 * OpenAPI spec version: 0.1
 */
import * as axios from "axios";
import type { AxiosRequestConfig, AxiosResponse } from "axios";
import type { WebLogout200 } from "../models";

/**
 * @summary Log out using an access token
 */
export const webLogout = <TData = AxiosResponse<WebLogout200>>(
  options?: AxiosRequestConfig,
): Promise<TData> => {
  return axios.default.delete(`/web/logout`, options);
};
export type WebLogoutResult = AxiosResponse<WebLogout200>;
