/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * logitry
 * OpenAPI spec version: 0.1
 */
import * as axios from "axios";
import type { AxiosRequestConfig, AxiosResponse } from "axios";
import type {
  Login200,
  LoginRequest,
  Me200,
  MeParams,
  SignIns200,
  SignInsParams,
} from "../models";

/**
 * @summary Log in using email/phone and password
 */
export const login = <TData = AxiosResponse<Login200>>(
  loginRequest: LoginRequest,
  options?: AxiosRequestConfig,
): Promise<TData> => {
  return axios.default.post(`/api/login`, loginRequest, options);
};
/**
 * @summary Get currently logged-in user
 */
export const me = <TData = AxiosResponse<Me200>>(
  params?: MeParams,
  options?: AxiosRequestConfig,
): Promise<TData> => {
  return axios.default.get(`/api/me`, {
    ...options,
    params: { ...params, ...options?.params },
  });
};
/**
 * @summary Retrieve a list of sign-in methods for a user based on email or phone.
 */
export const signIns = <TData = AxiosResponse<SignIns200>>(
  params?: SignInsParams,
  options?: AxiosRequestConfig,
): Promise<TData> => {
  return axios.default.get(`/api/sign-ins`, {
    ...options,
    params: { ...params, ...options?.params },
  });
};
export type LoginResult = AxiosResponse<Login200>;
export type MeResult = AxiosResponse<Me200>;
export type SignInsResult = AxiosResponse<SignIns200>;
