/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * logitry
 * OpenAPI spec version: 0.1
 */
import type { Company } from "./company";
import type { AvailableSignInRole } from "./availableSignInRole";

/**
 * Available sign-in object.
 */
export interface AvailableSignIn {
  company: Company;
  with_password: boolean;
  /** @nullable */
  role: AvailableSignInRole;
}
