/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * logitry
 * OpenAPI spec version: 0.1
 */

/**
 * @nullable
 */
export type AvailableSignInRole =
  | (typeof AvailableSignInRole)[keyof typeof AvailableSignInRole]
  | null;

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AvailableSignInRole = {
  Owner: "Owner",
  Admin: "Admin",
  Manager: "Manager",
} as const;
