/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * logitry
 * OpenAPI spec version: 0.1
 */

/**
 * The northeastern bound coordinates
 */
export type BoundsNorthEast = {
  /** Latitude of the northeastern point */
  latitude?: number;
  /** Longitude of the northeastern point */
  longitude?: number;
};
