/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * logitry
 * OpenAPI spec version: 0.1
 */

/**
 * The southwestern bound coordinates
 */
export type BoundsSouthWest = {
  /** Latitude of the southwestern point */
  latitude?: number;
  /** Longitude of the southwestern point */
  longitude?: number;
};
