/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * logitry
 * OpenAPI spec version: 0.1
 */
import type { BoundsNorthEast } from "./boundsNorthEast";
import type { BoundsSouthWest } from "./boundsSouthWest";

/**
 * Represents a set of geographical coordinates defining bounds
 */
export interface Bounds {
  /** The northeastern bound coordinates */
  northEast?: BoundsNorthEast;
  /** The southwestern bound coordinates */
  southWest?: BoundsSouthWest;
}
