/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * logitry
 * OpenAPI spec version: 0.1
 */

/**
 * The realm associated with the company
 * @nullable
 */
export type CompanyRealm =
  | (typeof CompanyRealm)[keyof typeof CompanyRealm]
  | null;

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CompanyRealm = {
  Logistics: "Logistics",
  Transfers: "Transfers",
} as const;
