/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * logitry
 * OpenAPI spec version: 0.1
 */

/**
 * Comma-separated list of fields to append to the resource.
              Available appends:
 */
export type CompanyAppends = string;
