/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * logitry
 * OpenAPI spec version: 0.1
 */
import type { CompanyRealm } from "./companyRealm";

/**
 * Company resource representation
 */
export interface Company {
  /** The unique identifier of the company */
  id?: number;
  /** The abbreviation of the company */
  abbreviation?: string;
  /** The name of the company */
  name?: string;
  /**
   * The realm associated with the company
   * @nullable
   */
  realm?: CompanyRealm;
  /**
   * The subscription plan of the company
   * @nullable
   */
  plan?: string | null;
  /**
   * The date and time the company was created
   * @nullable
   */
  created_at?: string | null;
  /**
   * The date and time the company was last updated
   * @nullable
   */
  updated_at?: string | null;
}
