/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * logitry
 * OpenAPI spec version: 0.1
 */
import type { Me } from "./me";

export type Login200Data = {
  token_type?: string;
  token?: string;
  expires_at?: string;
  /** @nullable */
  expires_in?: number | null;
  user?: Me;
};
