/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * logitry
 * OpenAPI spec version: 0.1
 */

/**
 * Request schema for logging in using credentials.
 */
export interface LoginRequest {
  /** Abbreviation of the company. Is required. */
  abbreviation: string;
  /** Email of the user. Required if 'phone' is not provided. */
  email?: string;
  /** Phone number of the user. Required if 'email' is not provided. */
  phone?: string;
  /** User's password. Is required. */
  password: string;
}
