/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * logitry
 * OpenAPI spec version: 0.1
 */
import type { Login200Data } from "./login200Data";

export type Login200 = {
  data?: Login200Data;
};
