/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * logitry
 * OpenAPI spec version: 0.1
 */
import type { MapBoundsNorthEast } from "./mapBoundsNorthEast";
import type { MapBoundsSouthWest } from "./mapBoundsSouthWest";

/**
 * Latitude and longitude bounds for trips
 */
export interface MapBounds {
  /** Northeast corner of the bounds */
  northEast: MapBoundsNorthEast;
  /** Southwest corner of the bounds */
  southWest: MapBoundsSouthWest;
}
