/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * logitry
 * OpenAPI spec version: 0.1
 */

/**
 * Southwest corner of the bounds
 */
export type MapBoundsSouthWest = {
  /** Minimum latitude value. */
  latitude: number;
  /** Minimum longitude value. */
  longitude: number;
};
