/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * logitry
 * OpenAPI spec version: 0.1
 */

/**
 * Northeast corner of the bounds
 */
export type MapBoundsNorthEast = {
  /** Maximum latitude value. */
  latitude: number;
  /** Maximum longitude value. */
  longitude: number;
};
