/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * logitry
 * OpenAPI spec version: 0.1
 */
import type { MeRole } from "./meRole";
import type { MeCompany } from "./meCompany";

/**
 * Representation of a logged-in User (me) model.
 */
export interface Me {
  /** Unique identifier for the user. */
  id?: number;
  /**
   * Unique identifier of the company.
   * @nullable
   */
  company_id?: number | null;
  /**
   * The name of the user.
   * @nullable
   */
  role?: MeRole;
  /**
   * The name of the user.
   * @nullable
   */
  name?: string | null;
  /**
   * The email address of the user.
   * @nullable
   */
  email?: string | null;
  /**
   * The phone number of the user.
   * @nullable
   */
  phone?: string | null;
  /**
   * Timestamp when the user's email was verified. Null if not verified.
   * @nullable
   */
  email_verified_at?: string | null;
  /**
   * Timestamp when the user's phone was verified. Null if not verified.
   * @nullable
   */
  phone_verified_at?: string | null;
  /**
   * Timestamp when the user was created.
   * @nullable
   */
  created_at?: string | null;
  /**
   * Timestamp when the user was last updated.
   * @nullable
   */
  updated_at?: string | null;
  /** @nullable */
  company?: MeCompany;
}
