/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * logitry
 * OpenAPI spec version: 0.1
 */
import type { Company } from "./company";

/**
 * @nullable
 */
export type MeCompany = Company | null;
