/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * logitry
 * OpenAPI spec version: 0.1
 */

/**
 * Comma-separated list of related resources to include with the resource.
              Available includes: `company`
 */
export type MeIncludes = string;
