/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * logitry
 * OpenAPI spec version: 0.1
 */
import type { MeIncludes } from "./meIncludes";
import type { MeAppends } from "./meAppends";

export type MeParams = {
  includes?: MeIncludes;
  appends?: MeAppends;
};
