/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * logitry
 * OpenAPI spec version: 0.1
 */

/**
 * The name of the user.
 * @nullable
 */
export type MeRole = (typeof MeRole)[keyof typeof MeRole] | null;

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const MeRole = {
  Owner: "Owner",
  Admin: "Admin",
  Manager: "Manager",
} as const;
