/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * logitry
 * OpenAPI spec version: 0.1
 */

/**
 * Determines if pagination should be omitted.
            The size parameter would be set to 1 million.
 */
export type PageOmit = number;
