/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * logitry
 * OpenAPI spec version: 0.1
 */
import type { PaginationLinks } from "./paginationLinks";

/**
 * Pagination meta object.
 */
export interface PaginationMeta {
  /** @nullable */
  from: number | null;
  /** @nullable */
  to: number | null;
  total: number;
  /** @nullable */
  path: number | null;
  per_page: number;
  current_page: number;
  last_page: number;
  links: PaginationLinks;
}
