/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * logitry
 * OpenAPI spec version: 0.1
 */

/**
 * Point resource representation
 */
export interface Point {
  /** Unique identifier for the point */
  id?: number;
  /** Identifier of the route associated with the point */
  route_id?: number;
  /** Point number in its sequence */
  number?: number;
  /**
   * Name of the point
   * @nullable
   */
  name?: string | null;
  /**
   * Description of the point
   * @nullable
   */
  description?: string | null;
  /**
   * Country where the point is located
   * @nullable
   */
  country?: string | null;
  /**
   * City where the point is located
   * @nullable
   */
  city?: string | null;
  /**
   * Street where the point is located
   * @nullable
   */
  street?: string | null;
  /** Latitude coordinate of the point */
  latitude?: number;
  /** Longitude coordinate of the point */
  longitude?: number;
  /**
   * Travel time to the point in minutes
   * @nullable
   */
  travel_time?: number | null;
  /**
   * Maximum allowed travel time to the point in minutes
   * @nullable
   */
  travel_time_cap?: number | null;
  /**
   * The date and time when the point was created
   * @nullable
   */
  created_at?: string | null;
  /**
   * The date and time when the point was last updated
   * @nullable
   */
  updated_at?: string | null;
}
