/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * logitry
 * OpenAPI spec version: 0.1
 */

/**
 * Sales
 */
export type RoutePriceUnit =
  (typeof RoutePriceUnit)[keyof typeof RoutePriceUnit];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RoutePriceUnit = {
  Seat: "Seat",
  Weight: "Weight",
  Volume: "Volume",
} as const;
