/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * logitry
 * OpenAPI spec version: 0.1
 */
import type { Bounds } from "./bounds";

/**
 * @nullable
 */
export type RouteBounds = Bounds | null;
