/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * logitry
 * OpenAPI spec version: 0.1
 */
import type { RoutePriceUnit } from "./routePriceUnit";
import type { RoutePriceRoute } from "./routePriceRoute";
import type { RoutePriceBegPoint } from "./routePriceBegPoint";
import type { RoutePriceEndPoint } from "./routePriceEndPoint";

/**
 * Representation of a RoutePrice
 */
export interface RoutePrice {
  /** Unique identifier for the route price */
  id?: number;
  /** Unique identifier for the associated route */
  route_id?: number;
  /**
   * Unique identifier for the beginning point of the route
   * @nullable
   */
  beg_point_id?: number | null;
  /**
   * Unique identifier for the endpoint of the route
   * @nullable
   */
  end_point_id?: number | null;
  /**
   * Name of the route price
   * @nullable
   */
  name?: string | null;
  /**
   * Description of the route price
   * @nullable
   */
  description?: string | null;
  /** Sales */
  unit?: RoutePriceUnit;
  /** Starting range price */
  from?: number;
  /**
   * Ending range price
   * @nullable
   */
  to?: number | null;
  /** Currency for the pricing */
  currency?: string;
  /**
   * Timestamp when the route price was created
   * @nullable
   */
  created_at?: string | null;
  /**
   * Timestamp when the route price was last updated
   * @nullable
   */
  updated_at?: string | null;
  /** @nullable */
  route?: RoutePriceRoute;
  /** @nullable */
  beg_point?: RoutePriceBegPoint;
  /** @nullable */
  end_point?: RoutePriceEndPoint;
}
