/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * logitry
 * OpenAPI spec version: 0.1
 */
import type { RouteCompany } from "./routeCompany";
import type { RouteContact } from "./routeContact";
import type { RouteVehicle } from "./routeVehicle";
import type { RouteDriver } from "./routeDriver";
import type { Point } from "./point";
import type { RouteBounds } from "./routeBounds";

/**
 * Representation of a Route
 */
export interface Route {
  /** Unique identifier for the route */
  id?: number;
  /** Identifier for the company associated with the route */
  company_id?: number;
  /**
   * Identifier for the contact person related to the route
   * @nullable
   */
  contact_id?: number | null;
  /**
   * Identifier for the vehicle used in the route
   * @nullable
   */
  vehicle_id?: number | null;
  /**
   * Identifier for the driver assigned to the route
   * @nullable
   */
  driver_id?: number | null;
  /**
   * Name of the route
   * @nullable
   */
  name?: string | null;
  /**
   * Details about the route
   * @nullable
   */
  description?: string | null;
  /**
   * Timestamp when the route was created
   * @nullable
   */
  created_at?: string | null;
  /**
   * Timestamp when the route was last updated
   * @nullable
   */
  updated_at?: string | null;
  /** @nullable */
  company?: RouteCompany;
  /**
   * Contact information associated with the route
   * @nullable
   */
  contact?: RouteContact;
  /**
   * Vehicle associated with the route
   * @nullable
   */
  vehicle?: RouteVehicle;
  /**
   * Driver of the route
   * @nullable
   */
  driver?: RouteDriver;
  /** Points included in the route */
  points?: Point[];
  /** @nullable */
  bounds?: RouteBounds;
}
