/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * logitry
 * OpenAPI spec version: 0.1
 */

/**
 * Driver of the route
 * @nullable
 */
export type RouteDriver = { [key: string]: unknown } | null;
