/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * logitry
 * OpenAPI spec version: 0.1
 */

/**
 * Vehicle associated with the route
 * @nullable
 */
export type RouteVehicle = { [key: string]: unknown } | null;
