/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * logitry
 * OpenAPI spec version: 0.1
 */
import type { AvailableSignIn } from "./availableSignIn";

export type SignIns200Data = {
  /** @nullable */
  email?: string | null;
  /** @nullable */
  phone?: string | null;
  sign_ins?: AvailableSignIn[];
};
