/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * logitry
 * OpenAPI spec version: 0.1
 */

export type SignInsParams = {
  /**
 * The phone number of the user. Is required without `email`.
                  Takes precedence over `email` if both are present.
 */
  phone?: string;
  /**
   * The email address of the user. Is required without `phone`.
   */
  email?: string;
};
