/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * logitry
 * OpenAPI spec version: 0.1
 */
import type { SignIns200Data } from "./signIns200Data";

export type SignIns200 = {
  data?: SignIns200Data;
};
