/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * logitry
 * OpenAPI spec version: 0.1
 */

/**
 * A comma-separated list of column names used for sorting results.
            <br><br>Ascending Order:<br>
            - Specify the column name directly (e.g., `sort=column`).
            <br>Example:<br> `sort=column` sorts by `column` in ascending order.
            <br><br>Multiple Columns:<br>
            - Specify multiple column names, separated by commas.
            <br>Example: `sort=column_one,column_two` sorts by `column_one` in ascending order,
            and then by `column_two` for records with identical `column_one` values.
            <br><br>Descending Order:<br>
            - Prefix the column name with a hyphen (`-`).
            <br>Example: `sort=-column` sorts by `column` in descending order.
            <br><br>Mixed Order:<br>
            - Use a combination of ascending and descending orders.
            <br>Example: `sort=column_one,-column_two` sorts by `column_one` in ascending order
            and then by `column_two` in descending order for records with identical `column_one` values.
 */
export type Sort = string;
