/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * logitry
 * OpenAPI spec version: 0.1
 */
import type { TripStatus } from "./tripStatus";
import type { TripPoint } from "./tripPoint";
import type { TripVehicle } from "./tripVehicle";
import type { TripDriver } from "./tripDriver";
import type { TripContact } from "./tripContact";

/**
 * Trip details
 */
export interface Trip {
  /** Unique identifier for the trip. */
  id: number;
  /** Type of the trip, e.g., Transfer. */
  type: string;
  /** Current status of the trip. */
  status: TripStatus;
  /** Name of the trip. */
  name: string;
  /** Description of the trip. */
  description: string;
  /** Date of the trip. */
  date: string;
  /** List of points in the trip route. */
  points: TripPoint[];
  vehicle: TripVehicle;
  driver: TripDriver;
  /** Total number of seats in the vehicle. */
  seats: number;
  /** Number of already booked seats. */
  seats_booked: number;
  /** Price per seat. */
  price: number;
  /** Currency for the price. */
  currency: string;
  contact: TripContact;
}
