/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * logitry
 * OpenAPI spec version: 0.1
 */

/**
 * Current status of the trip
 */
export type TripStatus = (typeof TripStatus)[keyof typeof TripStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const TripStatus = {
  Draft: "Draft",
  Available: "Available",
  Unavailable: "Unavailable",
  In_Progress: "In Progress",
  Finished: "Finished",
  Cancelled: "Cancelled",
} as const;
