/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * logitry
 * OpenAPI spec version: 0.1
 */

/**
 * Point of the trip route
 */
export interface TripPoint {
  /** City of the point. */
  city: string;
  /** Country of the point. */
  country: string;
  /**
   * Street address of the point.
   * @nullable
   */
  street: string | null;
  /** Scheduled time at this point. */
  time: string;
  /** Longitude coordinate. */
  longitude: number;
  /** Latitude coordinate. */
  latitude: number;
}
