/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * logitry
 * OpenAPI spec version: 0.1
 */

/**
 * Details of the trip's vehicle
 */
export interface TripVehicle {
  /** Vehicle identifier. */
  id: number;
  /** Manufacturer of the vehicle. */
  manufacturer: string;
  /** Model of the vehicle. */
  model: string;
  /** Year of manufacture. */
  year: string;
  /** Color of the vehicle. */
  color: string;
}
