/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * logitry
 * OpenAPI spec version: 0.1
 */

/**
 * Additional metadata for the trip
 * @nullable
 */
export type TripMetadata = { [key: string]: unknown } | null;
