/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * logitry
 * OpenAPI spec version: 0.1
 */

/**
 * Representation of a Trips Highlight
 */
export interface TripHighlight {
  /** Ids of the trips that are included in the count */
  ids?: number[];
  /** Departure date of the trips */
  date?: string;
  /** Number of trips on the given date */
  count?: number;
}
