/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * logitry
 * OpenAPI spec version: 0.1
 */
import type { TripStatus } from "./tripStatus";
import type { TripMetadata } from "./tripMetadata";

/**
 * Representation of a Trip
 */
export interface Trip {
  /** Unique identifier for the trip */
  id?: number;
  /** Identifier for the associated route */
  route_id?: number;
  /** Indicates if the route direction is reversed */
  reversed?: boolean;
  /**
   * Identifier for the vehicle assigned to the trip
   * @nullable
   */
  vehicle_id?: number | null;
  /**
   * Identifier for the driver assigned to the trip
   * @nullable
   */
  driver_id?: number | null;
  /**
   * Identifier for the contact person related to the trip
   * @nullable
   */
  contact_id?: number | null;
  /** Current status of the trip */
  status?: TripStatus;
  /**
   * Additional metadata for the trip
   * @nullable
   */
  metadata?: TripMetadata;
  /** Planned departure time of the trip */
  departs_at?: string;
  /**
   * Expected arrival time of the trip
   * @nullable
   */
  arrives_at?: string | null;
  /**
   * Timestamp when the trip was created
   * @nullable
   */
  created_at?: string | null;
  /**
   * Timestamp when the trip was last updated
   * @nullable
   */
  updated_at?: string | null;
}
