/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * logitry
 * OpenAPI spec version: 0.1
 */

/**
 * Current status of the trip.
 */
export type TripStatus = (typeof TripStatus)[keyof typeof TripStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const TripStatus = {
  Available: "Available",
  "Sold-Out": "Sold-Out",
  Cancelled: "Cancelled",
  Unavailable: "Unavailable",
} as const;
