/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * logitry
 * OpenAPI spec version: 0.1
 */

/**
 * Information about the driver
 */
export interface TripDriver {
  /** Driver identifier. */
  id: number;
  /** Name of the driver. */
  name: string;
  /** Driver contact number. */
  phone: string;
}
