/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * logitry
 * OpenAPI spec version: 0.1
 */

/**
 * Representation of a User model.
 */
export interface User {
  /** Unique identifier for the user. */
  id?: number;
  /** The name of the user. */
  name?: string;
  /**
   * The email address of the user.
   * @nullable
   */
  email?: string | null;
  /**
   * The phone number of the user.
   * @nullable
   */
  phone?: string | null;
  /**
   * Timestamp when the user's email was verified. Null if not verified.
   * @nullable
   */
  email_verified_at?: string | null;
  /**
   * Timestamp when the user's phone was verified. Null if not verified.
   * @nullable
   */
  phone_verified_at?: string | null;
  /**
   * Timestamp when the user was created.
   * @nullable
   */
  created_at?: string | null;
  /**
   * Timestamp when the user was last updated.
   * @nullable
   */
  updated_at?: string | null;
}
